### PR TITLE
Lang fixes, Spanish lang added, Follow Grav conventions

### PR DESCRIPTION
**Pull request by filisko**
Hi,
I just fixed some lang lines, added spanish translation and removed two lang lines (unnecessary I think) to follow Grav's admin panel convention which is: Admin nav option name <---> Admin page header name

Thank you!

### CODE REVIEW

**Comment by filisko** [comment]
I will do another pull request now.

**Comment by filisko** [comment]
OK, now it's better.
The thing was that the menu items were not translated properly because on the Group and User 'Manager' classes, you're translating before the language is detected, so it always gets translated to default.
https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/blob/master/src/Groups/Manager.php#L104

If you realize, in the admin panel view https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/nav.html.twig#L42
Here it already gets translated, so we have to pass only the lang 'key' as item label.

**Comment by filisko** [comment]
Hello?

**Comment by david-szabo97** [comment]
Thank you!!!!
I totally forgot about your PR, sorry about that :)

**Comment by filisko** [comment]
No problem! Thanks to you. :+1:

**Pull request merged**
